// <auto-generated />
namespace WorldNews.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Commentsandcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Commentsandcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201707190940192_Comments and category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
